
DROP PROCEDURE IF EXISTS PAPPARAITRE;
DELIMITER |
CREATE PROCEDURE PAPPARAITRE (IN VPOSITION INT, IN VID_RACINE INT, IN VID_ARTICLE INT, VID_ENTITE INT, IN VID_POS_TAG INT)   

BEGIN

     INSERT INTO APPARAITRE VALUES (NULL,VDATE_PUBLICATION,VID_JOURNAL,VID_CLASSE,VID_POSITIVE);

END|         

DELIMITER ;
CALL PAPPARAITRE("2017-12-31",1,1,1,@VID_ARTICLE);
CALL PAPPARAITRE("2018-01-26",1,1,2,VID_ARTICLE);
SELECT @VID_ARTICLE;

