DROP PROCEDURE IF EXISTS PAPPARTIENT;
DELIMITER |
CREATE PROCEDURE PAPPARTIENT (IN VID_ARTICLE INT, IN VID_CLASSE INT)   
BEGIN
	 
     INSERT INTO APPARTIENT VALUES (VID_ARTICLE ,VID_CLASSE);

END|         

DELIMITER ;
