
DROP PROCEDURE IF EXISTS PARTICLE;
DELIMITER |
CREATE PROCEDURE PARTICLE (IN VDATE_PUBLICATION DATE, IN VID_JOURNAL INT, IN VID_CLASSE INT, VID_POSITIVE INT, OUT VID_ARTICLE INT)   

BEGIN

     INSERT INTO ARTICLE VALUES (NULL,VDATE_PUBLICATION,VID_JOURNAL,VID_CLASSE,VID_POSITIVE);
     SELECT LAST_INSERT_ID() INTO VID_ARTICLE;

END|         

DELIMITER ;
CALL PARTICLE("2017-12-31",1,1,1,@VID_ARTICLE);
CALL PARTICLE("2018-01-26",1,1,2,@VID_ARTICLE);
SELECT @VID_ARTICLE;

