DROP PROCEDURE IF EXISTS particle/
	CREATE PROCEDURE particle (IN VDATE_PUBLICATION DATE, IN VRATE_POSITIVITY FLOAT,
	IN VRATE_NEGATIVITY FLOAT, IN VRATE_JOY FLOAT, IN VRATE_FEAR FLOAT, IN VRATE_SADNESS FLOAT,
	IN VRATE_ANGRY FLOAT, IN VRATE_SURPRISE FLOAT, IN VRATE_DISGUSS FLOAT, IN VID_NEWSPAPER INT, OUT VID_ARTICLE INT)

BEGIN

	INSERT INTO article (id_article, date_publication, rate_positivity, rate_negativity, rate_joy, 
	rate_fear, rate_sadness, rate_angry, rate_surprise, rate_disgust, id_newspaper) 
	VALUES (NULL,VDATE_PUBLICATION,VRATE_POSITIVITY,VRATE_NEGATIVITY,VRATE_JOY,VRATE_FEAR,
	VRATE_SADNESS,VRATE_ANGRY,VRATE_SURPRISE,VRATE_DISGUSS,VID_NEWSPAPER);
	SELECT LAST_INSERT_ID() INTO vid_article;

END/       

CALL particle("2017-12-31",0.10,0.11,0.12,0.13,0.14,0.15,0.16,0.17,1,@vid_article)/
SELECT @vid_article/
