DELIMITER /
DROP PROCEDURE IF EXISTS PAUTHOR/

CREATE PROCEDURE PAUTHOR (IN VID_ARTICLE INT, IN VSURNAME_AUTHOR VARCHAR(50), IN VFIRSTNAME_AUTHOR VARCHAR(50))   
BEGIN
	
	DECLARE COUNT_ID_ INT DEFAULT 0;
	DECLARE VID_AUTHOR INT DEFAULT 0;
	
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET VID_AUTHOR = NULL;

	SELECT AUTHOR.ID_AUTHOR INTO VID_AUTHOR
	FROM AUTHOR 
	WHERE AUTHOR.SURNAME_AUTHOR = VSURNAME_AUTHOR
	AND AUTHOR.FIRSTNAME_AUTHOR = VFIRSTNAME_AUTHOR;

	IF (VID_AUTHOR IS NULL)  THEN 
		INSERT INTO AUTHOR (ID_AUTHOR, SURNAME_AUTHOR, FIRSTNAME_AUTHOR) VALUES (NULL, VSURNAME_AUTHOR,VFIRSTNAME_AUTHOR);
    	SELECT LAST_INSERT_ID() INTO VID_AUTHOR;
	END IF;
	
    INSERT INTO REALIZE (ID_AUTHOR, ID_ARTICLE) VALUES (VID_AUTHOR ,VID_ARTICLE);

END/

CALL PAUTHOR('1', 'MICKA', 'ANJ');