DELIMITER /
DROP PROCEDURE IF EXISTS PAUTOR/

CREATE PROCEDURE PAUTOR (IN VSURNAME_AUTOR VARCHAR(50), IN VFIRSTNAME_AUTOR VARCHAR(50), OUT VID_AUTOR INT)   
BEGIN
     INSERT INTO AUTOR (ID_AUTOR, SURNAME_AUTOR, FIRSTNAME_AUTOR) VALUES (NULL, VSURNAME_AUTOR,VFIRSTNAME_AUTOR);
     SELECT LAST_INSERT_ID() INTO VID_AUTOR;
END/

CALL PAUTOR("jean","mich",@VID_AUTOR)/
CALL PAUTOR("be","fi",@VID_AUTOR)/
SELECT @VID_AUTOR/