DROP PROCEDURE IF EXISTS PBELONG;
DELIMITER |
CREATE PROCEDURE PBELONG (IN VID_ARTICLE INT, IN VID_LABEL INT)   
BEGIN
	 
     INSERT INTO BELONG (id_article,id_label) VALUES (VID_ARTICLE ,VID_LABEL);

END|         

DELIMITER ;
