DROP PROCEDURE IF EXISTS PCLASSIFICATION;
DELIMITER |
CREATE PROCEDURE PCLASSIFICATION (IN VCLASSE VARCHAR(50))
BEGIN
     INSERT INTO CLASSIFICATION VALUES (NULL,VCLASSE);
END|

DELIMITER ;
CALL PCLASSIFICATION("SPORT");
CALL PCLASSIFICATION("HUMOUR");

