DROP PROCEDURE IF EXISTS PECRIT;
DELIMITER |
CREATE PROCEDURE PECRIT (IN VID_AUTEUR INT, IN VID_ARTICLE INT)   
BEGIN
	 
     INSERT INTO ECRIT VALUES (VID_AUTEUR ,VID_ARTICLE);

END|         

DELIMITER ;
