DROP PROCEDURE IF EXISTS PENTITY;
DELIMITER |
CREATE PROCEDURE PENTITY (IN VENTITY VARCHAR(50))   
BEGIN
     INSERT INTO ENTITY VALUES (NULL,VENTITY);
END|         

DELIMITER ;
CALL PENTITY("PERSONNE");
CALL PENTITY("LIEU");

