
DROP PROCEDURE IF EXISTS PMOT;
DELIMITER |
CREATE PROCEDURE PMOT (IN VMOT VARCHAR(50), IN VRACINE VARCHAR(50), OUT VID_RACINE INT)   


BEGIN
DECLARE VID_MOT INT DEFAULT 0;

     INSERT INTO MOT VALUES (NULL,VMOT);
     
     SELECT ID_MOT INTO VID_MOT
     FROM MOT
     WHERE MOT=VMOT;

     INSERT INTO MOT_RACINE VALUES (NULL,VRACINE,VID_MOT);  

     SELECT ID_RACINE INTO VID_RACINE
     FROM MOT_RACINE
     WHERE MOT=VRACINE;

END|         

DELIMITER ;
CALL PMOT("VBA", "PYTHON", @ID_RACINE);
CALL PMOT("PHP", "JAVA", @ID_RACINE);
SELECT @ID_RACINE;
