DROP PROCEDURE IF EXISTS PNEWSPAPER;
DELIMITER |
CREATE PROCEDURE PNEWSPAPER (IN VNAME_NEWSPAPER VARCHAR(50),IN VLINK_NEWSPAPER VARCHAR(2083),IN VLINK_LOGO VARCHAR(2083))
BEGIN
     INSERT INTO NEWSPAPER VALUES (NULL,VNAME_NEWSPAPER,VLINK_NEWSPAPER,VLINK_LOGO);
END|

DELIMITER ;
CALL PNEWSPAPER("LIBERATION","HTTP liberation","http image");

