
DROP PROCEDURE IF EXISTS PPOSITIONWORD;
DELIMITER |
CREATE PROCEDURE PPOSITIONWORD (IN VPOSITION INT, IN VTITLE BOOLEAN, IN VID_WORD INT, VID_ENTITY INT, IN VID_POS_TAG INT, IN VID_ARTICLE INT,IN VID_SYNONYM INT,IN VID_WIKI INT)   

BEGIN

     INSERT INTO POSITION_MOT (ID_POSITION, POSITION,TITLE,ID_WORD,ID_ENTITY,ID_POS_TAG,ID_ARTICLE,ID_SYNONYM,ID_WIKI) 
     VALUES (NULL, VPOSITION,VTITLE,VID_WORD,VID_ENTITY,VID_POS_TAG,VID_ARTICLE,VID_SYNONYM,VID_WIKI);

END|         

DELIMITER ;
CALL PPOSITIONWORD(1,TRUE,1,1,1,1,1,1);
CALL PPOSITIONWORD(2,FALSE,2,1,1,1,1,1);
