
DROP PROCEDURE IF EXISTS PPOSITION_WORD;
DELIMITER |
CREATE PROCEDURE PPOSITION_WORD (IN VPOSITION INT, IN VTITLE BOOLEAN, IN VID_WORD INT, VID_ENTITY INT, IN VID_POS_TAG INT, IN VID_ARTICLE INT,IN VID_SYNONYM INT,IN VID_WIKI INT)   

BEGIN

     INSERT INTO POSITION_WORD (ID_POSITION, POSITION,TITLE,ID_WORD,ID_ENTITY,ID_POS_TAG,ID_ARTICLE,ID_SYNONYM,ID_WIKI) 
     VALUES (NULL, VPOSITION,VTITLE,VID_WORD,VID_ENTITY,VID_POS_TAG,VID_ARTICLE,VID_SYNONYM,VID_WIKI);

END|         

DELIMITER ;
CALL PPOSITION_WORD(18,TRUE,1,1,1,2,1,1);