
DROP PROCEDURE IF EXISTS PPOSITION_MOT;
DELIMITER |
CREATE PROCEDURE PPOSITION_MOT (IN VPOSITION INT, IN VTITRE BOOLEAN, IN VID_RACINE INT, VID_ENTITE INT, IN VID_POS_TAG INT, IN VID_ARTICLE INT)   

BEGIN

     INSERT INTO POSITION_MOT (ID_POSITION, POSITION,TITRE,ID_RACINE,ID_ENTITE,ID_POS_TAG,ID_ARTICLE) 
     VALUES (NULL, VPOSITION,VTITRE,VID_RACINE,VID_ENTITE,VID_POS_TAG, VID_ARTICLE);

END|         

DELIMITER ;
CALL PPOSITION_MOT(1,TRUE,1,1,1,1);
CALL PPOSITION_MOT(2,FALSE,2,1,1,1);
