DROP PROCEDURE IF EXISTS PREALIZE;
DELIMITER |
CREATE PROCEDURE PREALIZE (IN VID_AUTOR INT, IN VID_ARTICLE INT)   
BEGIN
	 
     INSERT INTO REALIZE (ID_AUTHOR, ID_ARTICLE) VALUES (VID_AUTOR ,VID_ARTICLE);

END|         

DELIMITER ;

CALL PREALIZE(1,2);