DROP PROCEDURE IF EXISTS PSYNONYM;
DELIMITER |
CREATE PROCEDURE PSYNONYM (IN VSYNONYM VARCHAR(50), IN VWORD VARCHAR(50))   
BEGIN
	DECLARE VID_SYNONYM INT DEFAULT 0;

	INSERT INTO SYNONYM (ID_SYNONYM, SYNONYM) VALUES (NULL,VSYNONYM);
    SELECT LAST_INSERT_ID() INTO VID_SYNONYM;

    UPDATE WORD
	SET WORD.ID_SYNONYM = VID_SYNONYM
	WHERE WORD.WORD = VWORD;

END|         

DELIMITER ;
CALL PSYNONYM("ESSAI","TEST");
CALL PSYNONYM("MACRON","PRESIDENT");
