DELIMITER /
DROP PROCEDURE IF EXISTS PWIKI/

CREATE PROCEDURE PWIKI (IN LIEN_WIKI VARCHAR(50), OUT VID_WIKI INT)   
BEGIN
     INSERT INTO WIKI (ID_WIKI, LIEN_WIKI) VALUES (NULL, LIEN_WIKI);
     SELECT LAST_INSERT_ID() INTO VID_WIKI;
END/

CALL PWIKI("wikipedia.org", @VID_WIKI)/
SELECT @VID_WIKI