
DROP PROCEDURE IF EXISTS PWORD;
DELIMITER |
CREATE PROCEDURE PWORD (IN VWORD VARCHAR(50), IN VLEMMA VARCHAR(50),IN VSYNONYM INT, OUT VID_WORD INT)   



BEGIN
DECLARE VID_LEMMA INT DEFAULT 0;
DECLARE VID_SYNONYM INT DEFAULT 0 ; 

    INSERT INTO SYNONYM (id_synonym ,synonym) VALUES (NULL , VSYNONYM);
    SELECT LAST_INSERT_ID() INTO VID_SYNONYM;
    INSERT INTO LEMMA (id_lemma,lemma) VALUES (NULL,VLEMMA);  
    SELECT LAST_INSERT_ID() INTO VID_LEMMA;
    INSERT INTO WORD (id_word,word,id_lemma,id_synonym) VALUES (NULL,VWORD, VID_LEMMA,VID_SYNONYM);
    SELECT LAST_INSERT_ID() INTO VID_WORD;

END|         

DELIMITER ;
CALL PWORD("VBA", "PYTHON","SQL", @ID_WORD);
CALL PWORD("PHP", "JAVA","CAML", @ID_WORD); 
SELECT @ID_WORD;
