
DROP PROCEDURE IF EXISTS PWORD;
DELIMITER |
CREATE PROCEDURE PWORD (IN VWORD VARCHAR(50), IN VLEMME VARCHAR(50), OUT VID_MOT INT)   



BEGIN
DECLARE VID_LEMME INT DEFAULT 0;


    INSERT INTO LEMME VALUES (NULL,VLEMME);  

    SELECT LAST_INSERT_ID() INTO VID_LEMME;

    INSERT INTO WORD VALUES (NULL,VWORD, VID_LEMME);

    SELECT LAST_INSERT_ID() INTO VID_WORD;

END|         

DELIMITER ;
CALL PWORD("VBA", "PYTHON", @ID_WORD);
CALL PWORD("PHP", "JAVA", @ID_WORD);
SELECT @ID_WORD;
