DROP PROCEDURE IF EXISTS PWRITE;
DELIMITER |
CREATE PROCEDURE PWRITE (IN VID_AUTOR INT, IN VID_ARTICLE INT)   
BEGIN
	 
     INSERT INTO ECRIT VALUES (VID_AUTOR ,VID_ARTICLE);

END|         

DELIMITER ;
