CREATE TRIGGER TREALIZE BEFORE INSERT
ON REALIZE FOR EACH ROW

BEGIN

   DECLARE nb1 int;
   DECLARE CLE_ETRANGERE CONDITION FOR SQLSTATE '99990';


   SELECT COUNT(A.id_author) INTO nb1
   FROM AUTHOR A
   WHERE NEW.id_author IN (SELECT id_author FROM author);
   
   IF (nb1=0)  THEN
   
	 SIGNAL CLE_ETRANGERE SET MESSAGE_TEXT = 'foreign key does not exist';

   END IF;

END |