DROP PROCEDURE IF EXISTS PPOSITIVITE;
DELIMITER |
CREATE PROCEDURE PPOSITIVITE (IN VPOSITIVITE BOOLEAN)
BEGIN
     INSERT INTO POSITIVITE VALUES (NULL,VPOSITIVITE);
END|

DELIMITER ;
CALL PPOSITIVITE(TRUE);
CALL PPOSITIVITE(FALSE);

