DELIMITER |
CREATE TRIGGER TWORD BEFORE INSERT
ON WORD FOR EACH ROW

BEGIN

   DECLARE nb1 int;
   DECLARE CLE_ETRANGERE CONDITION FOR SQLSTATE '99990';

   SELECT COUNT(L.id_lemma) INTO nb1
   FROM LEMMA L
   WHERE NEW.id_lemma IN (SELECT id_lemma FROM LEMMA);
   
   IF (nb1=0)  THEN
   
	 SIGNAL CLE_ETRANGERE SET MESSAGE_TEXT = 'foreign key does not exist';

   END IF;

END |

DELIMITER ;